---
title: "Bulk_Density"
author: "Harnay"
date: "2025-01-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Libraries
```{r}
library(tidyverse)
library(gridExtra)

```

Load data and metadata
```{r}
#load wax data
wax.data <- read.csv("Data/test_bulk_density_data.csv", header=TRUE)
colnames(wax.data) <- c("Sample.ID", "DW.clean.g", "DW.wax.g", "BW.wax.g", "Temperature.C", "Notes")
wax.data$Sample.ID <- as.character(wax.data$Sample.ID)

species.id <- read.csv("Data/test_Haplotype_data.csv", header=TRUE)
species.id$Species <- factor(species.id$Species)
species.id$Sample.ID <- as.character(species.id$Sample.ID)

metadata <- read.csv("/Users/hputnam/MyProjects/Pocillopora-Lagoon-Abundance/Data/POC_ID_RA_list.csv", header=TRUE) %>%
  select(c("Number", "Stage", "Timing", "Site", "Transect"))

colnames(metadata) <- c("Sample.ID", "Stage", "Timing", "Site", "Transect")
metadata$Sample.ID <- as.character(metadata$Sample.ID)

```

#Calculate surface area (Volume enclosed) using the standard curve
```{r}

#View the range of DW.clean.g
range(wax.data$DW.clean.g)
boxplot(wax.data$DW.clean.g)
hist(wax.data$DW.clean.g)

#View the range of DW.wax.g
range(wax.data$DW.wax.g)
boxplot(wax.data$DW.wax.g)
hist(wax.data$DW.wax.g)

wax.data <- wax.data %>%
  mutate(Vol.enc = DW.wax.g - BW.wax.g) %>%
  mutate(Bulk.Density = DW.clean.g/Vol.enc)

#check the range of bulk density values
#1.44 - 2.22 reported 10.7717/peerj.3191
range(wax.data$Bulk.Density)
boxplot(wax.data$Bulk.Density)
hist(wax.data$Bulk.Density)

```

Set species colors
```{r}

species_colors <- c("P. tuahiniensis" = "#D55E00",
                    "P. meandrina" = "pink",
                    "P. meandrina P. grandis" = "#0072B2",
                    "P. verrucosa" = "#E69F00",
                    "P. grandis" = "#56B4E9",
                    "P. effusa" = "#009E73",
                    "P. acuta" = "#e63946")



```

Plot by species and site
```{r}
data <- left_join(wax.data, species.id, by= "Sample.ID")
data <- left_join(data, metadata, by= "Sample.ID")

data$Species <- factor(data$Species, levels = c("P. tuahiniensis", 
                                                "P. meandrina", 
                                                "P. meandrina P. grandis", 
                                                "P. verrucosa", 
                                                "P. grandis", 
                                                "P. effusa", 
                                                "P. acuta"))

str(data)

#set site order
site_order <- c("S1","S2","S3","S4","S5","S6",
                "S9","S11","S12","S14","S15","S18")  

# Convert Site column to a factor with the custom order
data$Site <- factor(data$Site, levels = site_order)

# Check the structure to confirm the changes
str(data)


bulk.density.plot.raw <- data %>%
  ggplot(aes(x = Site, y = Bulk.Density, color = Species)) +  # Add 'color = Species' to map colors to the Species variable
  geom_point() +  # Plot the data points
  scale_color_manual(values = species_colors) +  # Apply the manual color scale
  facet_wrap(~ Species) +  # Facet by Species
  theme_bw()+
  labs(title="All Raw Data",
    x = "Species",
    y = "Bulk Density g/cm2"
  )  

bulk.density.plot.raw

```

```{r}

#remove max outlier
filtered_data <- data %>%
  filter(Bulk.Density != max(data$Bulk.Density, na.rm = TRUE))

bulk.density.plot.outlier.removed <- filtered_data %>%
  ggplot(aes(x = Site, y = Bulk.Density, color = Species)) +  # Add 'color = Species' to map colors to the Species variable
  geom_point() +  # Plot the data points
  scale_color_manual(values = species_colors) +  # Apply the manual color scale
  facet_wrap(~ Species) +  # Facet by Species
  theme_bw()+
  labs(title="Outlier Removed",
    x = "Species",
    y = "Bulk Density g/cm2"
  )  

bulk.density.plot.outlier.removed


bulk.density.plot.outlier.removed.species <- filtered_data %>%
  ggplot(aes(x = Site, y = Bulk.Density, color = Species, group = Species)) +  # Map color to Species
  geom_point(position = position_dodge(width = 0.9), size = 1, alpha = 0.2) +  # Plot the individual data points
  stat_summary(
    fun = "mean",  # Compute the mean
    geom = "point",  # Add the mean as a point
    size = 3,  # Size of the mean points
    shape = 18,  # Diamond shape for mean points
    aes(color = Species),  # Make the mean points the same color as the species
    position = position_dodge(width = 0.9)  # Dodge means to align with the individual points
  ) + 
  geom_line(
    stat = "summary",  # Use the summary statistics (mean) to plot the line
    fun = "mean",  # Line connects the means
    aes(group = Species, color = Species),  # Ensure the line connects the means of each species
    size = 1,  # Thickness of the line
  position = position_dodge(width = 0.9)) +
  scale_color_manual(values = species_colors) +  # Use your manual color palette for the species
  theme_classic() +  # Classic theme for cleaner look
  labs(
    title = "Outlier Removed",
    x = "Site",
    y = "Bulk Density g/cm²"
  )

# Display the plot
#bulk.density.plot.outlier.removed.species

```
View a single site
```{r}
#remove max outlier
site_filtered_data <- data %>%
  filter(Bulk.Density != max(data$Bulk.Density, na.rm = TRUE)) %>%
  filter(Site == "S2") %>%
  filter(Species != "NA")

bulk.density.plot.S2 <- site_filtered_data %>%
  ggplot(aes(x = Species, y = Bulk.Density, color = Species, group = Species)) +  # Add 'color = Species' to map colors to the Species variable
   geom_point(position = position_dodge(width = 0.9), size = 2, alpha = 0.3) +  # Plot the individual data points
  stat_summary(
    fun = "mean",  # Compute the mean
    geom = "point",  # Add the mean as a point
    size = 5,  # Size of the mean points
    shape = 18,  # Diamond shape for mean points
    aes(color = Species),  # Make the mean points the same color as the species
    position = position_dodge(width = 0.9)  # Dodge means to align with the individual points
  )+
  scale_color_manual(values = species_colors) +  # Apply the manual color scale
  geom_line(
    stat = "summary",  # Use the summary statistics (mean) to plot the line
    fun = "mean",  # Line connects the means
    aes(group = Species, color = Species),  # Ensure the line connects the means of each species
    size = 1,  # Thickness of the line
  position = position_dodge(width = 0.9)) +
  ylim(1.0, 2.4)+
  theme_bw()+
  labs(title="Single Site - Site 2",
    x = "Species",
    y = "Bulk Density g/cm2"
  )

bulk.density.plot.S2

```
View a single site
```{r}
#remove max outlier
site_filtered_data <- data %>%
  filter(Bulk.Density != max(data$Bulk.Density, na.rm = TRUE)) %>%
  filter(Site == "S14") %>%
  filter(Species != "NA")

bulk.density.plot.S14 <- site_filtered_data %>%
  ggplot(aes(x = Species, y = Bulk.Density, color = Species, group = Species)) +  # Add 'color = Species' to map colors to the Species variable
   geom_point(position = position_dodge(width = 0.9), size = 2, alpha = 0.3) +  # Plot the individual data points
  stat_summary(
    fun = "mean",  # Compute the mean
    geom = "point",  # Add the mean as a point
    size = 5,  # Size of the mean points
    shape = 18,  # Diamond shape for mean points
    aes(color = Species),  # Make the mean points the same color as the species
    position = position_dodge(width = 0.9)  # Dodge means to align with the individual points
  )+
  scale_color_manual(values = species_colors) +  # Apply the manual color scale
  geom_line(
    stat = "summary",  # Use the summary statistics (mean) to plot the line
    fun = "mean",  # Line connects the means
    aes(group = Species, color = Species),  # Ensure the line connects the means of each species
    size = 1,  # Thickness of the line
  position = position_dodge(width = 0.9)) +
  ylim(1.0, 2.4)+
  theme_bw()+
  labs(title="Single Site - Site 14",
    x = "Species",
    y = "Bulk Density g/cm2"
  )

bulk.density.plot.S14

```
View a single site
```{r}
#remove max outlier
site_filtered_data <- data %>%
  filter(Bulk.Density != max(data$Bulk.Density, na.rm = TRUE)) %>%
  filter(Site == "S15") %>%
  filter(Species != "NA")

bulk.density.plot.S15 <- site_filtered_data %>%
  ggplot(aes(x = Species, y = Bulk.Density, color = Species, group = Species)) +  # Add 'color = Species' to map colors to the Species variable
   geom_point(position = position_dodge(width = 0.9), size = 2, alpha = 0.3) +  # Plot the individual data points
  stat_summary(
    fun = "mean",  # Compute the mean
    geom = "point",  # Add the mean as a point
    size = 5,  # Size of the mean points
    shape = 18,  # Diamond shape for mean points
    aes(color = Species),  # Make the mean points the same color as the species
    position = position_dodge(width = 0.9)  # Dodge means to align with the individual points
  )+
  scale_color_manual(values = species_colors) +  # Apply the manual color scale
  geom_line(
    stat = "summary",  # Use the summary statistics (mean) to plot the line
    fun = "mean",  # Line connects the means
    aes(group = Species, color = Species),  # Ensure the line connects the means of each species
    size = 1,  # Thickness of the line
  position = position_dodge(width = 0.9)) +
  ylim(1.0, 2.4)+
  theme_bw()+
  labs(title="Single Site - Site 15",
    x = "Species",
    y = "Bulk Density g/cm2"
  )

bulk.density.plot.S15

```

plot to pdf
```{r}
# Save the plots to a PDF in one column
pdf("Output/BW.plots.pdf", height = 16, width = 10) # Set dimensions for the PDF
grid.arrange(bulk.density.plot.raw,
             bulk.density.plot.outlier.removed,
             bulk.density.plot.outlier.removed.species,
            ncol = 1) # Arrange in 1 column
dev.off() # Close the PDF device

# Save the plots to a PDF in one column
pdf("Output/BDSite.plots.pdf", height = 12, width = 10) # Set dimensions for the PDF
grid.arrange(bulk.density.plot.S2,
             bulk.density.plot.S14,
             bulk.density.plot.S15,
             ncol = 1) # Arrange in 1 column
dev.off() # Close the PDF device

```